In [3]:
from tensorflow.keras.models import load_model
import pickle

model = load_model('churn_model.h5')
with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('one_hot_encoder.pkl', 'rb') as f:
    one_hot_encoder = pickle.load(f)

In [4]:
input_data = {
    'Gender': 'Female',
    'Geography': 'France',
    'CreditScore': 600,
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [6]:
import pandas as pd

geo_encoded = one_hot_encoder.transform([['France']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df.head()

d:\Compelete datascience\ann project\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [16]:
# Use input_data directly since it's already a DataFrame
input_df = input_data
input_df

,Gender,Geography,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,France,600,40,3,60000,2,1,1,50000

In [15]:
input_df['Gender']=label_encoder.transform(input_df['Gender'])
input_df

,Gender,Geography,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,France,600,40,3,60000,2,1,1,50000

In [18]:
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_encoded_df], axis=1)
input_df

,Gender,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,0,600,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [22]:
# Ensure input_df columns are in the same order as scaler was fitted
expected_columns = scaler.feature_names_in_
input_df_ordered = input_df[expected_columns]

input_scaled = scaler.transform(input_df_ordered)
input_scaled

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [23]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 150ms/step

array([[0.04972234]], dtype=float32)

In [25]:
pred_prob=prediction[0][0]
pred_prob

0.049722344

In [26]:
if pred_prob > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.